name: ser_env
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch
  - torchaudio
  - transformers
  - scikit-learn
  - pandas
  - numpy
  - fastapi
  - uvicorn
  - pyyaml
  - python-multipart
  - pip
  - pip:
      - opensmile
